# Generated by Django 3.2.16 on 2023-01-17 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_post_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='File',
        ),
    ]
