# Generated by Django 3.2.16 on 2023-01-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20230124_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='background_pic',
            field=models.ImageField(blank=True, default='port-6.jpeg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
