# Generated by Django 3.2.16 on 2023-01-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_auto_20230124_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='background_pic',
            field=models.ImageField(blank=True, default='cover-photo.png', null=True, upload_to=''),
        ),
    ]
