# Generated by Django 3.2.16 on 2023-01-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_alter_account_background_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='background_pic',
            field=models.ImageField(blank=True, default='cover-photo_hVs4cgX_G9aAZgR.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_29hrBtO.png', null=True, upload_to=''),
        ),
    ]
